### ISSUE TITLE
Swing Timer - Attack Mod abilities aren't registered.

### ISSUE THREAD

**Issue by Foodlenz** [RichSteini/WeakAuras2-TBC-2.4.3#10]
## Describe the bug
When using an ability that modifies the next melee attack (heroic strike, cleave, raptor strike, maul, etc.) the swing timer doesn't register it as a melee swing and so the swing timer wont reset until the next white swing.

https://user-images.githubusercontent.com/72258441/224519017-78935abb-9463-4c14-9785-9ee440cd70b8.mp4

https://user-images.githubusercontent.com/72258441/224519019-00672db7-a0a8-4423-aa24-33e06c349386.mp4

**Comment by RichSteini** [comment]
SWING_DAMAGE or SWING_MISSED CLEU does not fire when you use a queue ability like the ones mentioned. I have to add them manually, are there any others than heroic strike, cleave, raptor strike, maul?

**Comment by RichSteini** [comment]
Implemented for heroic strike, cleave, raptor strike, maul in [Fix melee swing timers for queued spells, e.g., Heroic Strike](https://github.com/RichSteini/WeakAuras2-TBC-2.4.3/commit/be21171cf7d5ca30637cc60896c002a422a6c811). Another question is, do all of these spells work on mainhand and offhand swings?

**Comment by Foodlenz** [comment]
All of them should only work with the main hand swing.

**Comment by RichSteini** [comment]
I improved it in [Swing timer improvement, spellId lookup table](https://github.com/RichSteini/WeakAuras2-TBC-2.4.3/commit/51b3f14d856b670452aa375b7fe2c9bb1f7c2c05) with spellIds so it also works on clients with other languages. Dual wielding is still not perfect, but you cannot make it better on the 2.4.3 client, since everything is just with timings.
