### ISSUE TITLE
[Trigger][Spell] Action Usable - Mangle (Cat) 

### ISSUE THREAD

**Issue by Sattva-108** [RichSteini/WeakAuras2-TBC-2.4.3#9]
## Describe the bug

Trigger Action Usable - Mangle (Cat) doesn't work.
[Link for spell](https://www.wowhead.com/tbc/spell=33983/mangle-cat)

### To Reproduce

1. Create new Icon Weakaura
2. Make it in trigger: Spell - Action Usable - Type spell ID 33983
3. Try and see if it works.

**Which version of WeakAuras are you using?**

I'm using 4.0.0

### Video of bug reproduce on Stormforge TBC PTR (tried on another server too, its same)

https://user-images.githubusercontent.com/74269253/224484852-c92d5997-53ff-4d5e-80e8-02f16b2219de.mp4

**Comment by Sattva-108** [comment]
## UPDATE

Same goes for **[Mangle (Bear) Rank 3 ID 33987](https://www.wowhead.com/tbc/spell=33987/mangle-bear)**

**Comment by RichSteini** [comment]
Fixed in [Fix spellnames with parantheses like "Mangle (Bear)" adding ()](https://github.com/RichSteini/WeakAuras2-TBC-2.4.3/commit/329589b516b690582aaff63d32de2c0e23a112a0). This issue is related to the client only returning information about a spell with parantheses if you type for example "Mangle (Bear)()", so you have to add parantheses at the end. I don't know the reason, but the trigger works now as expected.
